/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Lib.XFile;
import Model.product;
import Model.order;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class homepage extends javax.swing.JFrame {
    CardLayout cardLayout;
    DefaultTableModel tbModel;
    DefaultTableModel tbModel2;
    Map<String, String> category;
    Map<String, product> menuProduct;
    int count = 0;
    DefaultComboBoxModel cbModel = new DefaultComboBoxModel();
    String filepath = "";
    String filepath2 = "";
    ArrayList<product> proList;
    ArrayList<order> orList;
    int currentRow = -1;
    
    
    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
        this.setLocationRelativeTo(null);
        cardLayout= (CardLayout) Panel.getLayout();
        category = new HashMap<>();
        menuProduct = new HashMap<>();
        initTabel();
        initTabe2();
        loadCb();
        rdSmall.setSelected(true);
        btnDeletePro.setEnabled(false);
        btnUpdatePro.setEnabled(false);
        btnAddPro.setEnabled(true);
        btnOAdd.setEnabled(true);
        btnODelete.setEnabled(false);
        btnOUpdate.setEnabled(false);
        txtTotal.setEnabled(false);
        txtProductPrice2.setEnabled(false);
        tbPro.setDefaultEditor(Object.class, null);
        filepath = "./src/Lib/product2.dat";
        filepath2 = "./src/Lib/order1.dat";
        proList = new ArrayList<>();
        orList = new ArrayList<>();
        boolean file = loadFile();
        boolean file2 = loadFile2();
        if (file) {
            fillToTable();
        }else{
            showMess("Nothing to show");
        }
        if (file2) {
            fillToTable2();
        }else{
            showMess("Nothing to show");
        }
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
        private void fillToTable(){
        tbModel.setRowCount(0);
        for (product p : proList){
            Object[] row = new Object[]{p.getCategoryName(),p.getProductCode(),p.getProductName(),p.getProductPrice()};
            tbModel.addRow(row);
        }
    }
        private void fillToTable2(){
           tbModel2.setRowCount(0);
           for (order o : orList){
            Object[] row = new Object[]{o.getCusName(),o.getCusPhone(),o.getCusAddress(),o.getoProduct(),o.getColor(),o.getTotal()};
            tbModel2.addRow(row);
        }
        }
    private void showMess(String mess){
        JOptionPane.showMessageDialog(this, mess);
    }
    private boolean loadFile(){
        if(XFile.readObject(filepath)==null){
            return false;
        }
        proList = (ArrayList<product>) XFile.readObject(filepath);
        return true;
    }
    
    private boolean loadFile2(){
    if(XFile.readObject(filepath2)==null){
        return false;
    }
        orList = (ArrayList<order>) XFile.readObject(filepath2);
        return true;
    }
    private void loadCb(){
        String[] proLst = {"Choose your food","Pizza","Hamburger"};
         int i = 0;
        for (String p : proLst) {
            category.put("M"+i, p);
            cbModel.addElement(p);
            i++;
        }
        cbCName.setModel(cbModel);   
    }
    private void initTabel(){
        String[] columNames = {"Category Name", "Product Code", "Product Name", "Product Price"};
        tbModel = new DefaultTableModel(columNames, 0);
        tbPro.setModel(tbModel); 
    }
    
      private void initTabe2(){
        String[] columNames = {"Customer Name", "Phone", "Address", "Product Name", "Size", "Total"};
        tbModel2 = new DefaultTableModel(columNames, 0);
        tbOrder.setModel(tbModel2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSize = new javax.swing.ButtonGroup();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbHome = new javax.swing.JLabel();
        lborder = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtCCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCName = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        txtPName = new javax.swing.JTextField();
        txtPPrice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPro = new javax.swing.JTable();
        btnRefesh = new javax.swing.JButton();
        btnAddPro = new javax.swing.JButton();
        btnUpdatePro = new javax.swing.JButton();
        btnDeletePro = new javax.swing.JButton();
        order = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbProductName2 = new javax.swing.JComboBox<>();
        txtProductPrice2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rdBig = new javax.swing.JRadioButton();
        rdMedium = new javax.swing.JRadioButton();
        rdSmall = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        txtCusPhone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnOAdd = new javax.swing.JButton();
        btnODelete = new javax.swing.JButton();
        btnOUpdate = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbOrder = new javax.swing.JTable();
        btnORefesh = new javax.swing.JButton();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbHome.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lbHome.setForeground(new java.awt.Color(255, 255, 255));
        lbHome.setText("Home");
        lbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbHomeMousePressed(evt);
            }
        });

        lborder.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lborder.setForeground(new java.awt.Color(255, 255, 255));
        lborder.setText("Order");
        lborder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lborderMousePressed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("____________________");

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        btnBack.setText("Exit");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoPiger.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnBack)
                        .addComponent(lborder, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHome)
                .addGap(18, 18, 18)
                .addComponent(lborder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );

        lbHome.getAccessibleContext().setAccessibleName("Jpanel1");

        Panel.setBackground(new java.awt.Color(255, 102, 102));
        Panel.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 204, 153));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 24))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Category ID");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Category Name");

        cbCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCCode, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(cbCName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel1.setText("HOME");

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 3, 24))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Product Code");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Price");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Product Name");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(37, 37, 37)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPID, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(txtPName)
                    .addComponent(txtPPrice))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tbPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbProMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbPro);

        btnRefesh.setBackground(new java.awt.Color(204, 255, 204));
        btnRefesh.setText("REFESH");
        btnRefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeshActionPerformed(evt);
            }
        });

        btnAddPro.setBackground(new java.awt.Color(153, 255, 51));
        btnAddPro.setText("ADD");
        btnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProActionPerformed(evt);
            }
        });

        btnUpdatePro.setBackground(new java.awt.Color(204, 255, 204));
        btnUpdatePro.setText("UPDATE");
        btnUpdatePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProActionPerformed(evt);
            }
        });

        btnDeletePro.setBackground(new java.awt.Color(204, 255, 204));
        btnDeletePro.setText("DELETE");
        btnDeletePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnRefesh)
                        .addGap(65, 65, 65)
                        .addComponent(btnAddPro)
                        .addGap(65, 65, 65)
                        .addComponent(btnUpdatePro)
                        .addGap(80, 80, 80)
                        .addComponent(btnDeletePro))
                    .addGroup(homeLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(homeLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefesh)
                    .addComponent(btnUpdatePro)
                    .addComponent(btnAddPro)
                    .addComponent(btnDeletePro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        Panel.add(home, "home");

        order.setBackground(new java.awt.Color(255, 204, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        jLabel2.setText("Order");

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information of Product", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Product Name");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Price");

        cbProductName2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProductName2ItemStateChanged(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 204, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Size", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        bgSize.add(rdBig);
        rdBig.setText("Big Size");
        rdBig.setActionCommand("Big");

        bgSize.add(rdMedium);
        rdMedium.setText("Medium Size");
        rdMedium.setActionCommand("Medium");

        bgSize.add(rdSmall);
        rdSmall.setText("Small Size");
        rdSmall.setActionCommand("Small");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdMedium)
                    .addComponent(rdBig)
                    .addComponent(rdSmall))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdBig)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdMedium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdSmall)
                .addGap(27, 27, 27))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Total");

        btnConfirm.setBackground(new java.awt.Color(255, 204, 153));
        btnConfirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbProductName2, 0, 149, Short.MAX_VALUE)
                    .addComponent(txtProductPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addGap(170, 170, 170))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbProductName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProductPrice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20))
        );

        jPanel6.setBackground(new java.awt.Color(255, 153, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Information Of Customer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Customer Name");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Phone Number");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Address");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane4.setViewportView(txtAddress);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel16))
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCusPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnOAdd.setBackground(new java.awt.Color(0, 255, 51));
        btnOAdd.setText("ADD");
        btnOAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOAddActionPerformed(evt);
            }
        });

        btnODelete.setBackground(new java.awt.Color(204, 255, 204));
        btnODelete.setText("DELETE");
        btnODelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnODeleteActionPerformed(evt);
            }
        });

        btnOUpdate.setBackground(new java.awt.Color(204, 255, 204));
        btnOUpdate.setText("UPDATE");
        btnOUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOUpdateActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 153, 102));

        tbOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbOrderMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(tbOrder);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnORefesh.setBackground(new java.awt.Color(204, 255, 204));
        btnORefesh.setText("REFESH");
        btnORefesh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnORefeshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderLayout = new javax.swing.GroupLayout(order);
        order.setLayout(orderLayout);
        orderLayout.setHorizontalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderLayout.createSequentialGroup()
                .addGroup(orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orderLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel2))
                    .addGroup(orderLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderLayout.createSequentialGroup()
                                .addComponent(btnOAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnODelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnOUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnORefesh))
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        orderLayout.setVerticalGroup(
            orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOAdd)
                    .addComponent(btnODelete)
                    .addComponent(btnOUpdate)
                    .addComponent(btnORefesh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        Panel.add(order, "order");
        order.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void lbHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHomeMousePressed
        // TODO add your handling code here:
        cardLayout.show(Panel, "home");
        txtProductPrice2.setText("");
    }//GEN-LAST:event_lbHomeMousePressed

    private void lborderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lborderMousePressed
        // TODO add your handling code here:
        cardLayout.show(Panel, "order");
        txtProductPrice2.setText("");
        proList.clear();
        cbProductName2.removeAllItems();
        proList = (ArrayList<product>) XFile.readObject(filepath);
        for (product p : proList) {  
            cbProductName2.addItem(p.getProductName());
            menuProduct.put(p.getProductPrice().toString(), p);
        }
       
    }//GEN-LAST:event_lborderMousePressed

    private void btnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProActionPerformed
        // TODO add your handling code here:
        if (CheckAll() == true) {
        addPro();
        fillToTable();
        saveFile();
        }
    }//GEN-LAST:event_btnAddProActionPerformed
    
    //check product
    private boolean CheckAll(){
        String pId = txtPID.getText();
        if(!"".equals(txtPID.getText()) && !"".equals(txtPName.getText())){
            for (product p : proList) {
                product pro = new product(p.getCategoryCode(),p.getCategoryName(),p.getProductCode(), p.getProductName(), p.getProductPrice());
                if (pId.equals(p.getProductCode())) {
                    txtPID.setBackground(Color.red);
                    return false;
                }
            }
            if ("".equals(txtPPrice.getText())) {
                txtPPrice.setBackground(Color.red);
                return false;
            }
            String price = txtPPrice.getText();
            for (int i = 0; i < price.length(); i++) {
            Boolean flags = Character.isDigit(price.charAt(i));
            if (!flags) {
                txtPPrice.setBackground(Color.red);
                return false;
            }
        }
    }else{
        txtPID.setBackground(Color.red);
        txtPName.setBackground(Color.red);
        txtPPrice.setBackground(Color.red);
        return false;
        }
        txtPID.setBackground(Color.white);
        txtPName.setBackground(Color.white);
        txtPPrice.setBackground(Color.white);
        return true;
    }
    
    //Check update product
    private boolean CheckUp(){
        String pName = txtPName.getText();
        String Price = txtPPrice.getText();
        if ("".equals(pName)) {
            txtPName.setBackground(Color.red);
            return false;
        }else if ("".equals(Price)) {
            txtPPrice.setBackground(Color.red);
            return false;
        }
        txtPName.setBackground(Color.white);
        txtPPrice.setBackground(Color.white);
        return true;
    }
    
    //Check update order
    private boolean CheckUp2(){
        String cusName = txtCusName.getText();
        String Phone = txtCusPhone.getText();
        String Address = txtAddress.getText();
        if ("".equals(cusName)) {
            txtCusName.setBackground(Color.red);
            return false;
        }else if ("".equals(Phone)) {
            txtCusPhone.setBackground(Color.red);
            return false;
        }else if ("".equals(Address)) {
            txtAddress.setBackground(Color.red);
            return false;
        }
        txtCusName.setBackground(Color.white);
        txtCusPhone.setBackground(Color.white);
        txtAddress.setBackground(Color.white);
        return true;
    }
    
    //check order
    private boolean CheckAll2(){
       String cusName = txtCusName.getText();
       String cusPhone =txtCusPhone.getText();
       String Address = txtAddress.getText();
        if (cusName.equals("") || cusPhone.equals("") || Address.equals("")) {
            txtCusName.setBackground(Color.red);
            txtCusPhone.setBackground(Color.red);
            txtAddress.setBackground(Color.red);
            return false;
        }
        txtCusName.setBackground(Color.white);
        txtCusPhone.setBackground(Color.white);
        txtAddress.setBackground(Color.white);
        return true;
    }
            
    private void cbCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCNameActionPerformed
        // TODO add your handling code here:
            String c = cbCName.getSelectedItem().toString();
        for (Map.Entry<String, String> entry : category.entrySet()) {
            if (entry.getValue().equals(c)){
                txtCCode.setText(entry.getKey());
                break;                         
            }
        }
    }//GEN-LAST:event_cbCNameActionPerformed

    private void btnDeleteProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProActionPerformed
        // TODO add your handling code here:
        btnAddPro.setEnabled(true);
        deletePro();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_btnDeleteProActionPerformed

    private void tbProMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProMousePressed
        // TODO add your handling code here:
        btnDeletePro.setEnabled(true);
        btnUpdatePro.setEnabled(true);
        btnAddPro.setEnabled(false);
        txtPID.setEnabled(false);
        currentRow = tbPro.getSelectedRow();
        showDetail(currentRow);
        txtCCode.setEditable(false);
    }//GEN-LAST:event_tbProMousePressed

    private void btnUpdateProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProActionPerformed
        // TODO add your handling code here:
        btnAddPro.setEnabled(true);
        txtPID.setEnabled(true);
        updatePro();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_btnUpdateProActionPerformed

    private void btnRefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeshActionPerformed
        // TODO add your handling code here:
        btnAddPro.setEnabled(true);
        txtPID.setEnabled(true);
        txtPID.setBackground(Color.white);
        txtPName.setBackground(Color.white);
        txtPPrice.setBackground(Color.white);
        resetForm();
        
    }//GEN-LAST:event_btnRefeshActionPerformed

    private void cbProductName2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProductName2ItemStateChanged
        // TODO add your handling code here:
        for (product p : proList) {  
                if(cbProductName2.getSelectedItem().toString().equals(p.getProductName())){
                    txtProductPrice2.setText(p.getProductPrice()+"");
                }
        }
    }//GEN-LAST:event_cbProductName2ItemStateChanged
    
    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        Double bPrice = Double.parseDouble(txtProductPrice2.getText())*0.35;
        Double mPrice = Double.parseDouble(txtProductPrice2.getText())*0.2;
        Double price = Double.parseDouble(txtProductPrice2.getText());
        if ("Big".equals(bgSize.getSelection().getActionCommand())) {
                txtTotal.setText(price + bPrice + "VND");
        }else if ("Medium".equals(bgSize.getSelection().getActionCommand())) {
                txtTotal.setText(price + mPrice + "VND");
        }else if ("Small".equals(bgSize.getSelection().getActionCommand())) {
                txtTotal.setText(price + "VND");
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnOAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOAddActionPerformed
        // TODO add your handling code here:
        if (CheckAll2() == true) {
            if ("".equals(txtTotal.getText())) {
                JOptionPane.showMessageDialog(this, "You have to press the confirm button");
                return;
            }
        addOrder();
        fillToTable2();
        saveFile2(); 
        resetForm2();
        }
    }//GEN-LAST:event_btnOAddActionPerformed

    private void btnODeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnODeleteActionPerformed
        // TODO add your handling code here:
        deleteOrder();
        fillToTable2();
        saveFile2();
    }//GEN-LAST:event_btnODeleteActionPerformed

    private void tbOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbOrderMousePressed
        // TODO add your handling code here:
        btnOAdd.setEnabled(false);
        btnODelete.setEnabled(true);
        btnOUpdate.setEnabled(true);
        currentRow = tbOrder.getSelectedRow();
        showDetail2(currentRow);
    }//GEN-LAST:event_tbOrderMousePressed

    private void btnOUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOUpdateActionPerformed
        // TODO add your handling code here:
        if (CheckUp2() == true) {
        updateOrder();
        fillToTable2();
        saveFile2();
        resetForm2();
        }
    }//GEN-LAST:event_btnOUpdateActionPerformed

    private void btnORefeshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnORefeshActionPerformed
        // TODO add your handling code here:
        resetForm2();
        btnOAdd.setEnabled(true);
        txtCusName.setBackground(Color.white);
        txtCusPhone.setBackground(Color.white);
        txtAddress.setBackground(Color.white);
    }//GEN-LAST:event_btnORefeshActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed
    
    private void updatePro(){
        if (CheckUp() == true) {
            
        product p = proList.get(currentRow);
        p.setCategoryName(cbCName.getSelectedItem().toString());
        p.setProductCode(txtPID.getText());
        p.setProductName(txtPName.getText());
        p.setProductPrice(Double.parseDouble(txtPPrice.getText()));
        resetForm();
        }
    }
    
    private void updateOrder(){
        order o = orList.get(currentRow);
        o.setCusName(txtCusName.getText());
        o.setCusPhone(txtCusPhone.getText());
        o.setCusAddress(txtAddress.getText());
        o.setoProduct(cbProductName2.getSelectedItem().toString());
        o.setTotal(Double.parseDouble(txtTotal.getText()));
    }
    
    private void deletePro(){
        int result = JOptionPane.showConfirmDialog(this, "Do you want to delete this?", "Delete",
                JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_NO_OPTION){
            proList.remove(currentRow);
            resetForm();
            txtPID.setEnabled(true);
        }
    } 
    
    private void deleteOrder(){
            int result = JOptionPane.showConfirmDialog(this, "Do you want to delete this?", "Delete",
                JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(result == JOptionPane.YES_NO_OPTION){
            orList.remove(currentRow);
            resetForm2();
            txtPID.setEnabled(true);
        }
    }
          
    private void resetForm(){
        btnDeletePro.setEnabled(false);
        btnUpdatePro.setEnabled(false);
        cbCName.setSelectedIndex(0);
        txtPID.setText("");
        txtPName.setText("");
        txtPPrice.setText("");
    }
    
    private void resetForm2(){
       cbProductName2.setSelectedIndex(0);
       txtCusName.setText("");
       txtCusPhone.setText("");
       txtAddress.setText("");
       txtTotal.setText("");
    }
    
    private void showDetail(int r){
    String cName = (String) tbPro.getValueAt(r, 0);
    cbCName.setSelectedItem(cName);
    String pId = (String) tbPro.getValueAt(r, 1);
    txtPID.setText(pId);
    String pName = (String) tbPro.getValueAt(r, 2);
    txtPName.setText(pName);
    Double pPrice = (Double) tbPro.getValueAt(r, 3);
    txtPPrice.setText(pPrice.toString());   
    }   
    
    
    private void showDetail2(int r){
    String cusName = (String) tbOrder.getValueAt(r, 0);
    txtCusName.setText(cusName);
    String Phone = (String) tbOrder.getValueAt(r, 1);
    txtCusPhone.setText(Phone);
    String Address = (String) tbOrder.getValueAt(r, 2);
    txtAddress.setText(Address);
    String pName2 = (String) tbOrder.getValueAt(r, 3);
    cbProductName2.setSelectedItem(pName2);
    String color = (String) tbOrder.getValueAt(r, 4);
    setBtnGroup(color); 
    Double Total = (Double) tbOrder.getValueAt(r, 5);
    txtTotal.setText(Total.toString());
    }   
    
    private void setBtnGroup(String value){
     for (Component c: jPanel3.getComponents()) {
         if(c instanceof JRadioButton){
             JRadioButton btn = (JRadioButton) c;
             if(btn.getActionCommand().equals(value)){
                 btn.setSelected(true);
             }
         }
     }
    }
    
    private void addPro(){ 
        String categoryCode = txtCCode.getText();
        String categoryName = cbCName.getSelectedItem().toString();
        String productCode = txtPID.getText();
        String productName = txtPName.getText().trim();
        Double productPrice = Double.parseDouble(txtPPrice.getText());
        product p = new product(categoryCode, categoryName, productCode, productName, productPrice);
        proList.add(p);
    }
    
    private void addOrder(){
        String cusName = txtCusName.getText();
        String cusPhone = txtCusPhone.getText();
        String cusAddress = txtAddress.getText();
        String oProduct = cbProductName2.getSelectedItem().toString();
        String Color = bgSize.getSelection().getActionCommand();
        Double total = Double.parseDouble(txtTotal.getText());
        order o = new order(cusName, cusPhone, cusAddress, oProduct, Color, total);
        orList.add(o);
    }

    private void saveFile(){
        XFile.writeObject(filepath, proList);
    }
    
    private void saveFile2(){
        XFile.writeObject(filepath2, orList);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.ButtonGroup bgSize;
    private javax.swing.JButton btnAddPro;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnDeletePro;
    private javax.swing.JButton btnOAdd;
    private javax.swing.JButton btnODelete;
    private javax.swing.JButton btnORefesh;
    private javax.swing.JButton btnOUpdate;
    private javax.swing.JButton btnRefesh;
    private javax.swing.JButton btnUpdatePro;
    private javax.swing.JComboBox<String> cbCName;
    private javax.swing.JComboBox<String> cbProductName2;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lborder;
    private javax.swing.JPanel order;
    private javax.swing.JRadioButton rdBig;
    private javax.swing.JRadioButton rdMedium;
    private javax.swing.JRadioButton rdSmall;
    private javax.swing.JTable tbOrder;
    private javax.swing.JTable tbPro;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCCode;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtCusPhone;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPName;
    private javax.swing.JTextField txtPPrice;
    private javax.swing.JTextField txtProductPrice2;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
